export const electionData = [
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ÁGUA BRANCA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "MARLUCE PEREIRA VERAS DE BRITO",
    "Nome Urna": "MARLUCE VERAS",
    "Partido / Coligação": "REPUBLICANOS / AVANÇA MAIS ÁGUA BRANCA",
    "Votação": 3.476,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "AGUIAR",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "MANOEL BATISTA GUEDES FILHO",
    "Nome Urna": "TINTIN",
    "Partido / Coligação": "PSB /  A VONTADE DO POVO",
    "Votação": 3.46,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ALAGOA GRANDE",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "JOAO BOSCO CARNEIRO NETO",
    "Nome Urna": "NETO CARNEIRO",
    "Partido / Coligação": "REPUBLICANOS / ALAGOA GRANDE PODE MAIS",
    "Votação": 9.191,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ALAGOA NOVA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "FRANCINILDO PIMENTEL DA SILVA",
    "Nome Urna": "FRANCINILDO PIMENTEL",
    "Partido / Coligação": "PSB / ALAGOA NOVA SEGUE EM FRENTE",
    "Votação": 11.402,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ALAGOINHA",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "ALIRIO CLAUDINO DE PONTES FILHO",
    "Nome Urna": "ALIRIO FILHO",
    "Partido / Coligação": "MDB / POR AMOR A ALAGOINHA",
    "Votação": 5.346,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ALCANTIL",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "CICERO JOSE FERNANDES DO CARMO",
    "Nome Urna": "CÍCERO DO CARMO",
    "Partido / Coligação": "PSD / SEGUE A TRANSFORMAÇÃO",
    "Votação": 3.236,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ALGODÃO DE JANDAÍRA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "HUMBERTO DOS SANTOS",
    "Nome Urna": "HUMBERTO",
    "Partido / Coligação": "PSB / UNIDOS POR ALGODÃO",
    "Votação": 1.843,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ALHANDRA",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "MARCELO RODRIGUES DA COSTA",
    "Nome Urna": "MARCELO RODRIGUES",
    "Partido / Coligação": "MDB / ALHANDRA AVANÇA COM O TRABALHO",
    "Votação": 11.885,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "AMPARO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "TARCIO GABRIEL ALVES DE BRITO RAFAEL",
    "Nome Urna": "TARCIO GABRIEL",
    "Partido / Coligação": "REPUBLICANOS / UNIDOS POR AMPARO",
    "Votação": 1.732,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "APARECIDA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOÃO RABELO DE SÁ NETO",
    "Nome Urna": "JOÃO NETO",
    "Partido / Coligação": "PSB / FAZENDO VALER A VONTADE DO POVO",
    "Votação": 4.943,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ARAÇAGI",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "JOSILDA MACENA BENÍCIO LEITE",
    "Nome Urna": "JOSILDA MACENA",
    "Partido / Coligação": "PSDB",
    "Votação": 7.754,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ARARA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "AMARILDO CARVALHO PEREIRA FILHO",
    "Nome Urna": "AMARILDO",
    "Partido / Coligação": "PSB",
    "Votação": 6.021,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ARARUNA",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "AVAILDO LUIS DE ALCÂNTARA AZEVEDO",
    "Nome Urna": "AVAILDO AZEVEDO",
    "Partido / Coligação": "PP / O TRABALHO SEGUE EM FRENTE",
    "Votação": 6.242,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "AREIA",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "SILVIA CESAR FARIAS DA CUNHA LIMA",
    "Nome Urna": "DRA. SILVIA",
    "Partido / Coligação": "MDB / RESPEITO, PAZ E LIBERDADE",
    "Votação": 6.179,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "AREIA DE BARAÚNAS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ANTONIO GERONIMO DUARTE MACEDO",
    "Nome Urna": "TOINHO MACEDO",
    "Partido / Coligação": "PSB / AREIA DE BARAÚNAS NO RUMO CERTO",
    "Votação": 1.378,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "AREIAL",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "CARLOS HENRIQUE PEREIRA BALBINO",
    "Nome Urna": "HENRIQUE",
    "Partido / Coligação": "PSDB",
    "Votação": 3.232,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "AROEIRAS",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "DOMINGOS MARQUES BARBOSA FILHO",
    "Nome Urna": "CÉSAR MARQUES",
    "Partido / Coligação": "PP / A FORÇA DO TRABALHO",
    "Votação": 9.059,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ASSUNÇÃO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "WAGNER FELIPE DE OLIVEIRA VILAR",
    "Nome Urna": "FELIPE",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 2.858,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BAÍA DA TRAIÇÃO",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "ELIZABETE DE OLIVEIRA",
    "Nome Urna": "DETA",
    "Partido / Coligação": "MDB / A FORÇA DO TRABALHO",
    "Votação": 5.208,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BANANEIRAS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "MATHEUS DE MELO BEZERRA CAVALCANTI",
    "Nome Urna": "MATHEUS BEZERRA",
    "Partido / Coligação": "PSB / SEGUE O RITMO DO TRABALHO",
    "Votação": 9.873,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BARAÚNA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "AUSTRYANEE JERONIMO DOS SANTOS",
    "Nome Urna": "AUSTRYANEE JERONIMO",
    "Partido / Coligação": "REPUBLICANOS / O trabalho tem que continuar",
    "Votação": 2.73,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BARRA DE SANTA ROSA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "ALEX SANDRO AZEVEDO VIEIRA",
    "Nome Urna": "ALEX  CONDA",
    "Partido / Coligação": "UNIÃO / COLIGAÇÃO UNIAO FORÇA E TRABALHO",
    "Votação": 5.134,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BARRA DE SANTANA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "CLEOCELIO NAZARENO BARRETO",
    "Nome Urna": "JUREMA",
    "Partido / Coligação": "UNIÃO / UNIDOS PODEMOS MAIS",
    "Votação": 3.239,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BARRA DE SÃO MIGUEL",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "JOÃO PAULO FRANÇA",
    "Nome Urna": "JOÃO PAULO",
    "Partido / Coligação": "PSD / O TRABALHO SEGUE FIRME",
    "Votação": 4.405,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BAYEUX",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "TARCYANNA MACEDO MOTA LEITÃO",
    "Nome Urna": "TACYANA LEITÃO",
    "Partido / Coligação": "PSB / PRA FAZER BAYEUX ACONTECER",
    "Votação": 28.09,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BELÉM",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "ALINE BARBOSA DE LIMA",
    "Nome Urna": "DONA ALINE",
    "Partido / Coligação": "MDB / TODOS JUNTOS POR BELÉM",
    "Votação": 6.091,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BELÉM DO BREJO DO CRUZ",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "LEOMAR JÂNIO DE MEDEIROS MAIA",
    "Nome Urna": "LEOMAR MAIA",
    "Partido / Coligação": "PL / JUNTOS, CONSTRUINDO O FUTURO",
    "Votação": 3.696,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BERNARDINO BATISTA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ANTONIO ALDO ANDRADE DE SOUSA",
    "Nome Urna": "ALDO ANDRADE",
    "Partido / Coligação": "PSB / ¿BERNARDINO BATISTA NO RUMO CERTO.¿",
    "Votação": 2.277,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BOA VENTURA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "MANOEL VITAL NETO",
    "Nome Urna": "VITAL",
    "Partido / Coligação": "REPUBLICANOS / PORQUE O POVO QUER",
    "Votação": 2.572,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BOA VISTA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "JOSÉ FERNANDO LEITE AIRES",
    "Nome Urna": "FERNANDO AIRES",
    "Partido / Coligação": "REPUBLICANOS / POR AMOR À BOA VISTA",
    "Votação": 2.703,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BOM JESUS",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "DENISE BANDEIRA DE MELO BARBOSA PEREIRA",
    "Nome Urna": "DENISE BAYMA",
    "Partido / Coligação": "PP / UNIDOS POR BOM JESUS",
    "Votação": 2.273,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BOM SUCESSO",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "MANOEL TAIRIS DUARTE",
    "Nome Urna": "TAIRIS DUARTE",
    "Partido / Coligação": "UNIÃO / COM DEUS, PEDRINHO E O POVO, BOM SUCESSO CONTINUARÁ SORRINDO",
    "Votação": 3.224,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BONITO DE SANTA FÉ",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ANTONIO LUCENA FILHO",
    "Nome Urna": "CENINHA LUCENA",
    "Partido / Coligação": "REPUBLICANOS / AVANÇA BONITO",
    "Votação": 3.917,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BOQUEIRÃO",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "JOÃO MARCOS DE FREITAS",
    "Nome Urna": "MARCOS FREITAS",
    "Partido / Coligação": "PSD / O TRABALHO CONTINUA",
    "Votação": 6.826,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BORBOREMA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "JOSÉ AMANCIO DA FONSÊCA RAMALHO",
    "Nome Urna": "AMANCINHO",
    "Partido / Coligação": "REPUBLICANOS / UNIÃO E TRABALHO POR BORBOREMA",
    "Votação": 2.152,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BREJO DO CRUZ",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "TALES TORRICELLI DE SOUSA COSTA E SILVA",
    "Nome Urna": "DR TALES",
    "Partido / Coligação": "PSDB",
    "Votação": 7.23,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "BREJO DOS SANTOS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "MARIA LUCIENE DE OLIVEIRA ALMEIDA",
    "Nome Urna": "LUCIENE",
    "Partido / Coligação": "PSB / PRA CONTINUAR CRESCENDO",
    "Votação": 2.85,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CAAPORÃ",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "FRANCISCO NAZARIO DE OLIVEIRA",
    "Nome Urna": "CHICO NAZARIO",
    "Partido / Coligação": "UNIÃO / Caaporã do futuro",
    "Votação": 6.809,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CABACEIRAS",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "RICARDO JORGE DE FARIAS AIRES",
    "Nome Urna": "RICARDO AIRES",
    "Partido / Coligação": "REPUBLICANOS / UNIDOS POR CABACEIRAS",
    "Votação": 3.385,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CABEDELO",
    "Cargo": "Prefeito",
    "Nº": 70,
    "Candidato": "ANDRE LUIS ALMEIDA COUTINHO",
    "Nome Urna": "ANDRE COUTINHO",
    "Partido / Coligação": "AVANTE / CABEDELO SEGUE AVANÇANDO",
    "Votação": 25.966,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CACHOEIRA DOS ÍNDIOS",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "ALYSON FRANCISCO DE MOURA SOUSA",
    "Nome Urna": "ALYSON FRANCISCO",
    "Partido / Coligação": "PP / UM NOVO RUMO PARA CACHOEIRA DOS ÍNDIOS",
    "Votação": 3.529,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CACIMBA DE AREIA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "HEITOR CARNEIRO CAMPOS",
    "Nome Urna": "HEITOR CAMPOS",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 2.758,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CACIMBA DE DENTRO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "POLLYANNO HENRIQUE PEREIRA",
    "Nome Urna": "POLLYANNO",
    "Partido / Coligação": "PSB / COM A FORÇA DO POVO, O TRABALHO SEGUE EM FRENTE",
    "Votação": 6.887,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CACIMBAS",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "NILTON DE ALMEIDA",
    "Nome Urna": "NILTON DE ALMEIDA",
    "Partido / Coligação": "REPUBLICANOS / O TRABALHO NÃO PODE PARAR",
    "Votação": 3.301,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CAIÇARA",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "TARCISIO ALBERTO LOPES SOARES",
    "Nome Urna": "TARCISINHO",
    "Partido / Coligação": "PL / CAIÇARA NO RUMO CERTO",
    "Votação": 3.669,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CAJAZEIRAS",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "MARIA DO SOCORRO DELFINO PEREIRA",
    "Nome Urna": "CORRINHA",
    "Partido / Coligação": "PP / Para a mudança continuar",
    "Votação": 20.521,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CAJAZEIRINHAS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "LUANA MARA DE ALMEIDA",
    "Nome Urna": "LUANA PIRES",
    "Partido / Coligação": "PSB / CAJAZEIRINHAS: UNIÃO E PROGRESSO",
    "Votação": 2.553,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CALDAS BRANDÃO",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "FÁBIO ROLIM PEIXOTO",
    "Nome Urna": "FÁBIO ROLIM",
    "Partido / Coligação": "MDB",
    "Votação": 2.705,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CAMALAÚ",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "UBIRAJARA ANTONIO PEREIRA MARIANO",
    "Nome Urna": "BIRA MARIANO",
    "Partido / Coligação": "PSB / UNIDOS POR CAMALAÚ",
    "Votação": 2.85,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CAMPINA GRANDE",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "BRUNO CUNHA LIMA BRANCO",
    "Nome Urna": "BRUNO CUNHA LIMA",
    "Partido / Coligação": "UNIÃO / UNIÃO POR AMOR A CAMPINA",
    "Votação": 110.807,
    "Situação": "2º turno"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CAMPINA GRANDE",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JHONY WESLLYS BEZERRA COSTA",
    "Nome Urna": "DR JHONY",
    "Partido / Coligação": "PSB / POR UMA CAMPINA CAMPEÃ",
    "Votação": 79.471,
    "Situação": "2º turno"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CAPIM",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "CARLYANNE SOARES BORBA",
    "Nome Urna": "CARLYANNE BORBA",
    "Partido / Coligação": "REPUBLICANOS / POR AMOR A CAPIM",
    "Votação": 3.637,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CARAÚBAS",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "NERIVAN ALVARES DE LIMA",
    "Nome Urna": "NERIVAN GARI",
    "Partido / Coligação": "MDB / CARAÚBAS PODE MAIS",
    "Votação": 2.276,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CARRAPATEIRA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "IARLEY PEREIRA BEZERRA",
    "Nome Urna": "IARLEY",
    "Partido / Coligação": "PSB",
    "Votação": 1.679,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CASSERENGUE",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ANTONIO JUDIVAN DE SOUSA",
    "Nome Urna": "VAN DE GALEGA",
    "Partido / Coligação": "PSB / FORÇA DO TRABALHO",
    "Votação": 3.027,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CATINGUEIRA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "SUELIO FELIX DE ALENCAR",
    "Nome Urna": "SUÉLIO",
    "Partido / Coligação": "UNIÃO / CATINGUEIRA NO RUMO CERTO",
    "Votação": 2.952,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CATOLÉ DO ROCHA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "LAURO ADOLFO MAIA SERAFIM",
    "Nome Urna": "LAURINHO MAIA",
    "Partido / Coligação": "UNIÃO / UNIDOS PARA AVANÇAR",
    "Votação": 15.213,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CATURITÉ",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "ITAMILSON FRANCISCO DA SILVA",
    "Nome Urna": "TITA DE BIU DOMINGOS",
    "Partido / Coligação": "PP / COLIGAÇÃO O FUTURO JÁ COMEÇOU!",
    "Votação": 2.994,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CONCEIÇÃO",
    "Cargo": "Prefeito",
    "Nº": 77,
    "Candidato": "SAMUEL SOARES LAVOR DE LACERDA",
    "Nome Urna": "SAMUEL LACERDA",
    "Partido / Coligação": "SOLIDARIEDADE / COMPROMISSO E PALAVRA!",
    "Votação": 6.095,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CONDADO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "CAIO RODRIGO BEZERRA PAIXÃO",
    "Nome Urna": "CAIO PAIXÃO",
    "Partido / Coligação": "REPUBLICANOS / CONDADO QUER O MELHOR",
    "Votação": 3.095,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CONDE",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "KARLA MARIA MARTINS PIMENTEL",
    "Nome Urna": "KARLA PIMENTEL",
    "Partido / Coligação": "PP / FÉ E POVO POR UM CONDE CADA VEZ MELHOR",
    "Votação": 14.41,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CONGO",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "FLAVIA EMANOELA SOUSA PEREIRA QUIRINO",
    "Nome Urna": "FLAVINHA",
    "Partido / Coligação": "MDB / COLIGAÇÃO FORTE É O POVO",
    "Votação": 2.924,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "COREMAS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "EDILSON PEREIRA DE OLIVEIRA",
    "Nome Urna": "EDILSON PEREIRA",
    "Partido / Coligação": "PSB / COLIGAÇÃO TRABALHO E RESPEITO PELO POVO",
    "Votação": 5.666,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "COXIXOLA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "NELSON JOSÉ NEVES HONORATO",
    "Nome Urna": "NELSINHO HONORATO",
    "Partido / Coligação": "UNIÃO / A FORÇA DO TRABALHO",
    "Votação": 1.633,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CRUZ DO ESPÍRITO SANTO",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "ALINY CIBELY CUNHA DA SILVA FARIAS",
    "Nome Urna": "ALINY POVÃO",
    "Partido / Coligação": "UNIÃO / FORÇA DO POVO",
    "Votação": 9.893,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CUBATI",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOSE RIBEIRO DE OLIVEIRA",
    "Nome Urna": "RIBEIRO",
    "Partido / Coligação": "PSB / UNIDOS SOMOS MAIS FORTES",
    "Votação": 4.496,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CUITÉ",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "CAIO TIBÉRIO BARBALHO INÁCIO DA SILVA",
    "Nome Urna": "CAIO CAMARAENSE",
    "Partido / Coligação": "PP / BORA FAZER MAIS",
    "Votação": 9.29,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CUITÉ DE MAMANGUAPE",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "HÉLIO SEVERINO DE SOUZA",
    "Nome Urna": "HELHINHO SOUZA",
    "Partido / Coligação": "MDB / TRABALHANDO COM AMOR",
    "Votação": 3.633,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CUITEGI",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "GUILHERME CUNHA MADRUGA JUNIOR",
    "Nome Urna": "GUILHERME MADRUGA",
    "Partido / Coligação": "PSB / SEMPRE JUNTOS POR CUITEGI",
    "Votação": 2.886,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CURRAL DE CIMA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ADJAMIR SOUZA DA SILVA",
    "Nome Urna": "ADJAMIR",
    "Partido / Coligação": "PSB / UM NOVO TEMPO DE TRABALHO",
    "Votação": 3.009,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "CURRAL VELHO",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "TÁCIO SAMUEL BARBOSA DINIZ",
    "Nome Urna": "TÁCIO SAMUEL BARBOSA DINIZ",
    "Partido / Coligação": "MDB / CURRAL VELHO SEGUE AVANÇANDO",
    "Votação": 1.735,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "DAMIÃO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "SIMONE DE AZEVEDO SANTOS CASADO",
    "Nome Urna": "SIMONE AZEVEDO",
    "Partido / Coligação": "PSB / O AVANÇO CONTINUA",
    "Votação": 2.344,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "DESTERRO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "TIAGO SIMÕES DOS SANTOS",
    "Nome Urna": "TIAGO",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 3.869,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "DIAMANTE",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "HERMES MANGUEIRA DINIZ FILHO",
    "Nome Urna": "HERMES FILHO",
    "Partido / Coligação": "MDB / CONSTRUINDO COM O TRABALHO",
    "Votação": 2.488,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "DONA INÊS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ANTONIO JUSTINO DE ARAUJO NETO",
    "Nome Urna": "ANTONIO JUSTINO",
    "Partido / Coligação": "PSB / A FORÇA DO TRABALHO",
    "Votação": 4.113,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "DUAS ESTRADAS",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "MYLLENA NAYARA LEANDRO NUNES",
    "Nome Urna": "MYLLENA",
    "Partido / Coligação": "PSD / MAIS TRABALHO E MAIS CUIDADO",
    "Votação": 1.937,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "EMAS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ANA ALVES DE ARAÚJO LOUREIRO",
    "Nome Urna": "ANETE LOUREIRO",
    "Partido / Coligação": "PSB / UNIDOS PELO TRABALHO",
    "Votação": 2.007,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ESPERANÇA",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "THIAGO DE ASSIS MORAES",
    "Nome Urna": "THIAGO MORAES",
    "Partido / Coligação": "PP / FRENTE PROGRESSISTA POPULAR DE ESPERANÇA",
    "Votação": 11.808,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "FAGUNDES",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "WILMAR LEMOS MARANHÃO JÚNIOR",
    "Nome Urna": "JÚNIOR MARANHÃO",
    "Partido / Coligação": "PSB / COLIGAÇÃO RENOVAÇÃO DA ESPERANÇA FAGUNDENSE",
    "Votação": 4.991,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "FREI MARTINHO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "SEBASTIÃO PINTO DANTAS",
    "Nome Urna": "TIÃO PINTO",
    "Partido / Coligação": "REPUBLICANOS / O TRABALHO SEGUE EM FRENTE",
    "Votação": 2.186,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "GADO BRAVO",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "MARCELO PAULINO DA SILVA",
    "Nome Urna": "MARCELO JORGE",
    "Partido / Coligação": "PL / POR AMOR A GADO BRAVO",
    "Votação": 3.73,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "GUARABIRA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "MARIA HAILEA ARAUJO TOSCANO",
    "Nome Urna": "LÉA TOSCANO",
    "Partido / Coligação": "UNIÃO / VONTADE DO POVO",
    "Votação": 18.059,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "GURINHÉM",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "TARCISIO SAULO DE PAIVA",
    "Nome Urna": "TARCISIO",
    "Partido / Coligação": "PSB / POR AMOR A GURINHÉM",
    "Votação": 5.321,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "GURJÃO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOSÉ ELIAS BORGES BATISTA",
    "Nome Urna": "ZÉ ELIAS",
    "Partido / Coligação": "PSB / COLIGAÇÃO HUMILDADE, TRABALHO E UNIÃO.",
    "Votação": 1.766,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "IBIARA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "LUCINEIDE VIEIRA PEREIRA",
    "Nome Urna": "LÚ PEREIRA",
    "Partido / Coligação": "PSB / O TRABALHO CONTINUA COM A FORÇA DA MULHER!",
    "Votação": 2.918,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "IGARACY",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "EDNAILTON SABINO DA SILVA",
    "Nome Urna": "EDNAILTON SABINO",
    "Partido / Coligação": "PSB / A FORÇA DO TRABALHO",
    "Votação": 2.649,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "IMACULADA",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "ALDO LUSTOSA DA SILVA",
    "Nome Urna": "DADA",
    "Partido / Coligação": "PSD / COLIGAÇÃO DE MÃOS DADAS COM DEUS E O POVO",
    "Votação": 4.677,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "INGÁ",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "JANDERSON DE OLIVEIRA CHAVES",
    "Nome Urna": "JAN DE MANOEL DA LENHA",
    "Partido / Coligação": "PL",
    "Votação": 5.672,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ITABAIANA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "JOSE CLAUDIO CHAVES CAVALCANTE NETO",
    "Nome Urna": "DR CLAUDIO NETO",
    "Partido / Coligação": "REPUBLICANOS / A VOZ DO POVO CADA VEZ MAIS FORTE",
    "Votação": 9.81,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ITAPORANGA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "AZIF DAVI LEMOS",
    "Nome Urna": "DR AZIF",
    "Partido / Coligação": "PSB / UNIÃO, TRABALHO E AVANÇO",
    "Votação": 11.346,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ITAPOROROCA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "JOAO BATISTA SANTOS DA SILVA",
    "Nome Urna": "BATISTA TORRES",
    "Partido / Coligação": "UNIÃO / Com a Força do Povo",
    "Votação": 7.141,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ITATUBA",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "JOSMAR LACERDA MARTINS",
    "Nome Urna": "JOSMAR LACERDA",
    "Partido / Coligação": "MDB / JUNTOS POR ITATUBA",
    "Votação": 3.991,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JACARAÚ",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "MÁRCIO AURELIO MADRUGA CRUZ",
    "Nome Urna": "MÁRCIO AURÉLIO",
    "Partido / Coligação": "PSD / JACARAÚ PODE MAIS",
    "Votação": 5.735,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JERICÓ",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "KADSON VALBERTO LOPES MONTEIRO",
    "Nome Urna": "KADSON MONTEIRO",
    "Partido / Coligação": "PSB / POR AMOR A JERICO",
    "Votação": 3.76,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JOÃO PESSOA",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "CICERO DE LUCENA FILHO",
    "Nome Urna": "CICERO LUCENA",
    "Partido / Coligação": "PP / JOÃO PESSOA NO CAMINHO CERTO",
    "Votação": 205.122,
    "Situação": "2º turno"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JOÃO PESSOA",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "MARCELO ANTONIO CARTAXO QUEIROGA LOPES",
    "Nome Urna": "MARCELO QUEIROGA",
    "Partido / Coligação": "PL / COLIGAÇÃO PRA MUDAR JOÃO PESSOA DE VERDADE",
    "Votação": 90.84,
    "Situação": "2º turno"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JOCA CLAUDINO",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "RINALDO CIPRIANO DE SOUSA",
    "Nome Urna": "RINALDO CIPRIANO",
    "Partido / Coligação": "MDB",
    "Votação": 1.745,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JUAREZ TÁVORA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "WILSON EVANGELISTA FEITOSA",
    "Nome Urna": "WILSON",
    "Partido / Coligação": "PSB / O TRABALHO CONTINUA",
    "Votação": 4.917,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JUAZEIRINHO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ANNA VIRGINIA DE BRITO MATIAS",
    "Nome Urna": "ANNA VIRGÍNIA",
    "Partido / Coligação": "REPUBLICANOS / JUAZEIRINHO EM 1º LUGAR",
    "Votação": 8.607,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JUNCO DO SERIDÓ",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "PAULO NEIDE MELO FRAGOSO",
    "Nome Urna": "DR PAULO",
    "Partido / Coligação": "PSB / JUNCO AINDA MELHOR",
    "Votação": 4.056,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JURIPIRANGA",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "ANTONIO MAROJA GUEDES FILHO",
    "Nome Urna": "TOM MAROJA",
    "Partido / Coligação": "PSDB",
    "Votação": 5.066,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "JURU",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "SOLANGE MARIA FELIX BARBOSA",
    "Nome Urna": "SOLANGE FÉLIX",
    "Partido / Coligação": "PSB / TRABALHO E COMPROMISSO DE VERDADE",
    "Votação": 4.465,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "LAGOA",
    "Cargo": "Prefeito",
    "Nº": 12,
    "Candidato": "MARIA RODRIGUES LINHARES DE LIMA",
    "Nome Urna": "SOCORRO DE BIRÓ",
    "Partido / Coligação": "PDT",
    "Votação": 3.16,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "LAGOA DE DENTRO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "CAMAF DOUGLAS DA SILVA MOREIRA",
    "Nome Urna": "CAMAF",
    "Partido / Coligação": "REPUBLICANOS / Uma Nova Lagoa de Dentro",
    "Votação": 2.765,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "LAGOA SECA",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "MICHELLE RIBEIRO DO NASCIMENTO",
    "Nome Urna": "MICHELLE",
    "Partido / Coligação": "PSDB",
    "Votação": 10.941,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "LASTRO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "RONALDO GONCALVES SOARES SOBRINHO",
    "Nome Urna": "DR RONALDO",
    "Partido / Coligação": "REPUBLICANOS / LASTRO SEGUE UNIDO",
    "Votação": 2.575,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "LIVRAMENTO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ERNANDES BARBOZA NÓBREGA",
    "Nome Urna": "NANANDA BARBOZA",
    "Partido / Coligação": "PSB / LIVRAMENTO NUM SÓ CORAÇÃO",
    "Votação": 3.288,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "LOGRADOURO",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "JOSÉ MARINALDO DA CRUZ",
    "Nome Urna": "MARINALDO CRUZ",
    "Partido / Coligação": "MDB / LOGRADOURO DAQUI PRA FRENTE",
    "Votação": 2.613,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "LUCENA",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "LEOMAX DA COSTA BANDEIRA",
    "Nome Urna": "LÉO",
    "Partido / Coligação": "MDB / LUCENA SEGUE AVANÇANDO",
    "Votação": 5.599,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MÃE D'ÁGUA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "JUCELIO PEREIRA MOURA",
    "Nome Urna": "DR JUCELIO",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 1.949,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MALTA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ANA MARIA PEIXOTO DE ARAUJO",
    "Nome Urna": "ANA PEIXOTO",
    "Partido / Coligação": "REPUBLICANOS / NOSSO COMPROMISSO SEGUE SENDO O TRABALHO",
    "Votação": 3.842,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MAMANGUAPE",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOAQUIM FERNANDES DE OLIVEIRA NETO",
    "Nome Urna": "JOAQUIM",
    "Partido / Coligação": "PSB / O TRABALHO SEGUE EM FRENTE",
    "Votação": 18.114,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MANAÍRA",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "MANOEL VIRGULINO SIMÃO",
    "Nome Urna": "DR MESSIAS",
    "Partido / Coligação": "PSDB",
    "Votação": 4.102,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MARCAÇÃO",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "ELLYS SÔNIA OLIVEIRA GOMES DA SILVA",
    "Nome Urna": "NINHA",
    "Partido / Coligação": "PSD / O TRABALHO CONTINUA",
    "Votação": 4.922,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MARI",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "LUCIA DE FATIMA SANTOS DA SILVA",
    "Nome Urna": "LUCINHA DA SAÚDE",
    "Partido / Coligação": "PSB / O TRABALHO CONTINUA",
    "Votação": 7.621,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MARIZÓPOLIS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "LUCAS GONÇALVES BRAGA",
    "Nome Urna": "LUQUINHA DO BRASIL",
    "Partido / Coligação": "PSB / O TRABALHO CONTNUA",
    "Votação": 3.202,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MASSARANDUBA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "JOÃO COSTA DE SOUSA",
    "Nome Urna": "JOÃO COSTA",
    "Partido / Coligação": "UNIÃO / QUEM TEM FÉ SEMPRE VENCE",
    "Votação": 7.68,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MATARACA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "EYMARD DE ARAÚJO PEDROSA",
    "Nome Urna": "EYMARD",
    "Partido / Coligação": "PSB / COMPETÊNCIA, UNIÃO E TRABALHO",
    "Votação": 4.187,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MATINHAS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "BENEDITO BRAZ DA SILVA",
    "Nome Urna": "BENEDITO",
    "Partido / Coligação": "PSB / O TRABALHO CONTINUA",
    "Votação": 2.996,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MATO GROSSO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "GIDALVA FRANCISCA DE LIMA",
    "Nome Urna": "GIDALVA",
    "Partido / Coligação": "PSB",
    "Votação": 2.037,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MATURÉIA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ELIANDRO MACEDO SANTOS",
    "Nome Urna": "LEANDRO LAIA",
    "Partido / Coligação": "REPUBLICANOS / UNIDOS POR MATUREIA",
    "Votação": 2.625,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MOGEIRO",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "ANTONIO JOSE FERREIRA",
    "Nome Urna": "ANTONIO FERREIRA",
    "Partido / Coligação": "PL / POR AMOR A MOGEIRO",
    "Votação": 5.369,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MONTADAS",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "JOSE ROMERO MARTINS DOS SANTOS",
    "Nome Urna": "ROMERO MARTINS",
    "Partido / Coligação": "PSD / PARA CUIDAR DE TODOS",
    "Votação": 2.475,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MONTE HOREBE",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "MILENA KAREN TAVARES NOGUEIRA",
    "Nome Urna": "MILENA",
    "Partido / Coligação": "MDB",
    "Votação": 2.459,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MONTEIRO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ANA PAULA BARBOSA OLIVEIRA MORATO",
    "Nome Urna": "ANA PAULA",
    "Partido / Coligação": "PSB / MONTEIRO AVANÇA CADA VEZ MAIS",
    "Votação": 12.608,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "MULUNGU",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "DANIELA RODRIGUES RIBEIRO",
    "Nome Urna": "DANIELA RIBEIRO",
    "Partido / Coligação": "REPUBLICANOS / UNIDOS POR MULUNGU",
    "Votação": 4.58,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "NATUBA",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "JOSE LINS DA SILVA FILHO",
    "Nome Urna": "LINSINHO",
    "Partido / Coligação": "PSDB",
    "Votação": 4.305,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "NAZAREZINHO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "MARCELO BATISTA VALE",
    "Nome Urna": "MARCELO VALE",
    "Partido / Coligação": "REPUBLICANOS / NAZAREZINHO NO MELHOR CAMINHO",
    "Votação": 3.927,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "NOVA FLORESTA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOSE IRAN DOS SANTOS",
    "Nome Urna": "IRAN SANTOS",
    "Partido / Coligação": "PSB / O TRABALHO PRECISA CONTINUAR",
    "Votação": 3.819,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "NOVA OLINDA",
    "Cargo": "Prefeito",
    "Nº": 12,
    "Candidato": "CICERO DAVID DE ANDRADE",
    "Nome Urna": "CICERO DE ARLETE",
    "Partido / Coligação": "PDT",
    "Votação": 2.339,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "NOVA PALMEIRA",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "ANTÔNIO ORLANDO PEREIRA DE ARAÚJO",
    "Nome Urna": "ORLANDO PEREIRA",
    "Partido / Coligação": "MDB / POR AMOR A NOVA PALMEIRA",
    "Votação": 1.717,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "OLHO D'ÁGUA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOANA SABINO DE ALMEIDA CARVALHO",
    "Nome Urna": "JOANA SABINO",
    "Partido / Coligação": "PSB / A FORÇA DO TRABALHO",
    "Votação": 3.706,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "OLIVEDOS",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "PEDRO JARSON VERISSIMO DE SOUZA",
    "Nome Urna": "GERSON",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 2.134,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "OURO VELHO",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "GILVANEY JOSÉ VENÂNCIO DA SILVA JÚNIOR",
    "Nome Urna": "DR. JÚNIOR",
    "Partido / Coligação": "UNIÃO / AVANTE COM O TRABALHO",
    "Votação": 2.345,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PARARI",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "GENIVAL AIRES DE QUEIROZ FILHO",
    "Nome Urna": "GENIVAL QUEIROZ",
    "Partido / Coligação": "PL / PARARI SEGUE EM FRENTE",
    "Votação": 1.549,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PASSAGEM",
    "Cargo": "Prefeito",
    "Nº": 18,
    "Candidato": "ROZÂNGELA FERREIRA SILVA",
    "Nome Urna": "TENENA",
    "Partido / Coligação": "REDE",
    "Votação": 1.751,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PATOS",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "NABOR WANDERLEY DA NOBREGA FILHO",
    "Nome Urna": "NABOR",
    "Partido / Coligação": "REPUBLICANOS / Coligação Para Patos Continuar Mudando",
    "Votação": 37.613,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PAULISTA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "LUCAS DE SOUSA PEREIRA",
    "Nome Urna": "LUCAS PEREIRA",
    "Partido / Coligação": "PSB / PAULISTA UNIDA PELO FUTURO",
    "Votação": 5.051,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PEDRA BRANCA",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "ALLISON VICTO BASTOS DE SOUSA",
    "Nome Urna": "BASTINHO",
    "Partido / Coligação": "MDB / O TRABALHO CONTINUA",
    "Votação": 2.631,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PEDRA LAVRADA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "JOSE ANTONIO VASCONCELOS DA COSTA",
    "Nome Urna": "TOTA GUEDES",
    "Partido / Coligação": "UNIÃO / O TRABALHO É DE VERDADE",
    "Votação": 3.874,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PEDRAS DE FOGO",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "JOSÉ CARLOS FERREIRA BARROS",
    "Nome Urna": "BÁ BARROS",
    "Partido / Coligação": "MDB / Presente de trabalho. Futuro de novas conquistas.",
    "Votação": 13.533,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PEDRO RÉGIS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "MICHELE RIBEIRO DE OLIVEIRA",
    "Nome Urna": "MICHELE RIBEIRO",
    "Partido / Coligação": "PSB / O melhor vem agora",
    "Votação": 3.25,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PIANCÓ",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "JÚLIO EDUARDO VENÂNCIO PINHEIRO",
    "Nome Urna": "JULHINHO",
    "Partido / Coligação": "PP / PRA FRENTE, PIANCÓ!",
    "Votação": 6.531,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PICUÍ",
    "Cargo": "Prefeito",
    "Nº": 13,
    "Candidato": "JOSÉ RANIERI SANTOS FERREIRA",
    "Nome Urna": "RANIERI",
    "Partido / Coligação": "PT",
    "Votação": 6.716,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PILAR",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "PATRICIA RODRIGUES SILVA OLIVEIRA DE FARIAS",
    "Nome Urna": "PATRICIA FARIAS",
    "Partido / Coligação": "PSD / É DAQUI PARA MLEHOR, PILAR",
    "Votação": 5.775,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PILÕES",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "SORAYA FERREIRA SALES DA CUNHA",
    "Nome Urna": "SORAYA",
    "Partido / Coligação": "PP / Pilões Seguindo em Frente",
    "Votação": 3.155,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PILÕEZINHOS",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "MARCELO MATIAS CAMELO",
    "Nome Urna": "MARCELO MATIAS",
    "Partido / Coligação": "MDB / PELO POVOE COM O POVO, A LUTA CONTINUA",
    "Votação": 2.919,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PIRPIRITUBA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "DANILO CALIXTO DE FREITAS ROCHA",
    "Nome Urna": "DANILO",
    "Partido / Coligação": "UNIÃO / CORAGEM PRA SEGUIR EM FRENTE",
    "Votação": 3.715,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PITIMBU",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ADELMA CRISTOVAM DOS PASSOS",
    "Nome Urna": "PROFESSORA ADELMA",
    "Partido / Coligação": "PSB / PITIMBU CONTINUARÁ A BRILHAR",
    "Votação": 6.986,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "POCINHOS",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ELIANE MOURA DOS SANTOS GALDINO",
    "Nome Urna": "ELIANE GALDINO",
    "Partido / Coligação": "REPUBLICANOS / A LUTA CONTINUA",
    "Votação": 9.678,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "POÇO DANTAS",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ITAMAR MOREIRA FERNANDES",
    "Nome Urna": "ITAMAR MOREIRA",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 2.987,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "POÇO DE JOSÉ DE MOURA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "LAIS RAQUEL DANTAS DE OLIVEIRA",
    "Nome Urna": "LAIS RAQUEL",
    "Partido / Coligação": "PSB / \"CORAGEM PARA MUDAR",
    "Votação": 2.321,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "POMBAL",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "CLAUDENILDO ALENCAR NÓBREGA",
    "Nome Urna": "GALEGO DA GAVEL",
    "Partido / Coligação": "REPUBLICANOS / Coligação Experiência e Trabalho Aprovado",
    "Votação": 10.946,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PRATA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "GENIVALDO FERNANDES DA SILVA",
    "Nome Urna": "GENIVALDO TEMBÓRIO",
    "Partido / Coligação": "REPUBLICANOS / UNIDOS PELA PRATA",
    "Votação": 2.796,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PRINCESA ISABEL",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "EDNALDO DE MELO",
    "Nome Urna": "GARRANCHO",
    "Partido / Coligação": "PSB / JUNTOS POR PRINCESA",
    "Votação": 7.988,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "PUXINANÃ",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ELEUZA MARIA DE OLIVEIRA",
    "Nome Urna": "ELEUZA",
    "Partido / Coligação": "REPUBLICANOS / SEGUE O TRABALHO",
    "Votação": 6.876,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "QUEIMADAS",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "DELÚSIA BARROS DA SILVA",
    "Nome Urna": "DELÚSIA BARROS",
    "Partido / Coligação": "REPUBLICANOS / COM CORAGEM E UNIÃO, QUEIMADAS AVANÇA",
    "Votação": 19.529,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "QUIXABA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ALLAN D'LLON CANDEIA DE MACEDO",
    "Nome Urna": "ALLAN",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 1.841,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "REMÍGIO",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "LUIS CLAUDIO RÉGIS MARINHO",
    "Nome Urna": "CLAUDIO RÉGIS",
    "Partido / Coligação": "PP / UNIDOS POR UMA REMÍGIO MELHOR",
    "Votação": 6.173,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "RIACHÃO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "DONATO APARECIDO DE AQUINO",
    "Nome Urna": "DONATO",
    "Partido / Coligação": "PSB",
    "Votação": 1.623,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "RIACHÃO DO BACAMARTE",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOSE DE ARIMATEA DA SILVA",
    "Nome Urna": "ARI",
    "Partido / Coligação": "PSB / ¿O TRABALHO NÃO PARA, A MUDANÇA CONTINUA¿",
    "Votação": 3.396,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "RIACHÃO DO POÇO",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "MARCELO FERREIRA DE LIMA",
    "Nome Urna": "MARCELO",
    "Partido / Coligação": "UNIÃO / UNIDOS POR UMA RIACHAO CADA VEZ MELHOR",
    "Votação": 2.45,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "RIACHO DE SANTO ANTÔNIO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "MARCELO BARBOSA FERREIRA",
    "Nome Urna": "MARCELO BARBOSA",
    "Partido / Coligação": "REPUBLICANOS / O AVANÇO E O TRABALHO CONTINUAM",
    "Votação": 1.938,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "RIACHO DOS CAVALOS",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "ARTHUR VIEIRA CARNEIRO",
    "Nome Urna": "ARTHUR VIEIRA",
    "Partido / Coligação": "PP / UM NOVO TEMPO DE TRABALHO",
    "Votação": 3.929,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "RIO TINTO",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "MAGNA CELI FERNANDES GERBASI",
    "Nome Urna": "MAGNA GERBASI",
    "Partido / Coligação": "PP / RIO TINTO SEGUE AVANÇANDO",
    "Votação": 8.928,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SALGADINHO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ERIVAN JÚLIO DA SILVA",
    "Nome Urna": "ERIVAN JÚLIO",
    "Partido / Coligação": "PSB / PARA SALGADINHO CONTINUAR AVANÇANDO",
    "Votação": 1.835,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SALGADO DE SÃO FÉLIX",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "JONI MARCOS SOUZA DE OLIVEIRA",
    "Nome Urna": "DR JONI",
    "Partido / Coligação": "REPUBLICANOS / SALGADO NO CAMINHO CERTO",
    "Votação": 4.895,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTA CECÍLIA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOSE MARCILIO FARIAS DA SILVA",
    "Nome Urna": "MARCILIO",
    "Partido / Coligação": "PSB / UNIDOS POS SANTA CECILIA",
    "Votação": 3.166,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTA CRUZ",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "ALBERTO DUARTE DE SOUSA",
    "Nome Urna": "ALBERTO DE BRAZ",
    "Partido / Coligação": "PL / O TRABALHO SEGUE EM FRENTE",
    "Votação": 3.552,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTA HELENA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "JOÃO CLEBER FERREIRA LIMA",
    "Nome Urna": "JOÃO CLEBER",
    "Partido / Coligação": "PSB / \"SANTA HELENA NÃO PODE PARAR",
    "Votação": 3.289,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTA INÊS",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "FELIX HENRIQUE LEITE VIEIRA",
    "Nome Urna": "FELIX VIEIRA",
    "Partido / Coligação": "UNIÃO / SANTA INÊS NO RUMO CERTO",
    "Votação": 2.425,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTA LUZIA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "HENRY MALDINEY DE LIRA NÓBREGA",
    "Nome Urna": "HENRY LIRA",
    "Partido / Coligação": "REPUBLICANOS / A TRANSFORMAÇÃO CONTINUA",
    "Votação": 5.905,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTA RITA",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "JACKSON ALVINO DA COSTA",
    "Nome Urna": "JACKSON",
    "Partido / Coligação": "PP / 100% MELHOR PRA SANTA RITA",
    "Votação": 38.241,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTA TERESINHA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "JOSE DE ARIMATEIA NUNES CAMBOIM",
    "Nome Urna": "ARIMATEIA CAMBOIM",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 2.768,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTANA DE MANGUEIRA",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "MARINA DONÁRIA ALVARENGA DE LACERDA",
    "Nome Urna": "MARINA LACERDA",
    "Partido / Coligação": "MDB / O TRABALHO CONTINUA",
    "Votação": 2.783,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTANA DOS GARROTES",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "PALOMA KENNED LEITE DA SILVA",
    "Nome Urna": "PALOMA",
    "Partido / Coligação": "REPUBLICANOS / UM FUTURO DE MAIS CONQUISTAS",
    "Votação": 4.126,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SANTO ANDRÉ",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "EDGLEI AMORIM DO NASCIMENTO",
    "Nome Urna": "EDGLEI AMORIM",
    "Partido / Coligação": "PP / SEGUE O TRABALHO",
    "Votação": 1.683,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO BENTINHO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "GIOVANA LEITE CAVALCANTI OLÍMPIO",
    "Nome Urna": "GIOVANA OLÍMPIO",
    "Partido / Coligação": "REPUBLICANOS / Unidos pelo trabalho",
    "Votação": 2.709,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO BENTO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "GERFERSON GARCIA DE SOUSA",
    "Nome Urna": "GERFESON CARNAÚBA",
    "Partido / Coligação": "PSB / SÃO BENTO AVANÇA PARA UM FUTURO SEGURO",
    "Votação": 14.196,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO DOMINGOS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ADEILZA SOARES FREIRES",
    "Nome Urna": "ADEILZA SOARES",
    "Partido / Coligação": "PSB / SÃO DOMINGOS LIVRE PARA CONTINUAR CRESCENDO",
    "Votação": 1.597,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO DOMINGOS DO CARIRI",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "ONILDO LINDBERG ANANIAS DA SILVA",
    "Nome Urna": "ONILDO",
    "Partido / Coligação": "PSD / PARA SÃO DOMINGOS DO CARIRI CONTINUAR CRESCENDO",
    "Votação": 1.972,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO FRANCISCO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "GERONCIO SUCUPIRA JUNIOR",
    "Nome Urna": "GERONCIO JUNIOR",
    "Partido / Coligação": "REPUBLICANOS / SÃO FRANCISCO CADA VEZ MELHOR",
    "Votação": 2.32,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOÃO DO CARIRI",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "FRANCISCO JOAQUIM DE LUCENA PEREIRA",
    "Nome Urna": "CHICO DE EULINA",
    "Partido / Coligação": "UNIÃO / FÉ TRABALHO E UNIÃO POR SÃO JOÃO",
    "Votação": 2.325,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOÃO DO RIO DO PEIXE",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "LUIZ CLAUDINO DE CARVALHO FLORENCIO",
    "Nome Urna": "LUIZ CLAUDINO",
    "Partido / Coligação": "PSB / TRABALHO TESTADO E APROVADO",
    "Votação": 9.985,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOÃO DO TIGRE",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "MÁRCIO ALEXANDRE LEITE",
    "Nome Urna": "MÁRCIO LEITE",
    "Partido / Coligação": "REPUBLICANOS / TRABALHO, LIBERDADE E INOVAÇÃO",
    "Votação": 2.673,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DA LAGOA TAPADA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "EVILASIO FORMIGA LUCENA NETO",
    "Nome Urna": "NETO DE CORACI",
    "Partido / Coligação": "REPUBLICANOS / JUVENTUDE E COMPROMISSO",
    "Votação": 3.081,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DE CAIANA",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "MANOEL PEREIRA DE SOUZA",
    "Nome Urna": "MANOEL MOLEQUE",
    "Partido / Coligação": "PL / O TRABALHO CONTINUA",
    "Votação": 3.16,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DE ESPINHARAS",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "THAISE GOMES DE SOUSA",
    "Nome Urna": "THAISE DE EDJANE",
    "Partido / Coligação": "PP / SEGUE O TRABALHO",
    "Votação": 2.922,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DE PIRANHAS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "SANDOVAL VIEIRA LINS",
    "Nome Urna": "BAL LINS",
    "Partido / Coligação": "PSB / SÃO JOSÉ DE PIRANHAS NO RUMO CERTO",
    "Votação": 8.83,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DE PRINCESA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "JULIANO DINIZ DE MORAIS",
    "Nome Urna": "JULIANO MATUTO",
    "Partido / Coligação": "REPUBLICANOS / O PROGRESSO CONTINUA",
    "Votação": 2.175,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DO BONFIM",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "ROSALBA GOMES DA NOBREGA MOTA",
    "Nome Urna": "ROSALBA MOTA",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 2.907,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DO BREJO DO CRUZ",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "KLEDYANNE CRISTINA DA SILVA GOMES",
    "Nome Urna": "KLEDYANNE",
    "Partido / Coligação": "PL / POR UMA SÃO JOSÉ CADA VEZ MELHOR",
    "Votação": 1.532,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DO SABUGI",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "EMANUEL DE ARAÚJO DOMICIANO DANTAS",
    "Nome Urna": "EMANUEL DOMICIANO",
    "Partido / Coligação": "UNIÃO / PARA SÃO JOSÉ SEGUIR AVANÇANDO",
    "Votação": 3.196,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DOS CORDEIROS",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "FELÍCIO KELMO ALMEIDA QUEIROZ",
    "Nome Urna": "FELÍCIO QUEIROZ",
    "Partido / Coligação": "PL / POR AMOR A SÃO JOSÉ DOS CORDEIROS",
    "Votação": 2.856,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO JOSÉ DOS RAMOS",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "MATHEUS AMORIM MARANHAO E SILVA",
    "Nome Urna": "MATHEUS AMORIM",
    "Partido / Coligação": "REPUBLICANOS / O POVO QUER",
    "Votação": 3.721,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO MAMEDE",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "FRANCISCO DAS CHAGAS LOPES DE SOUZA FILHO",
    "Nome Urna": "CHAGUINHA",
    "Partido / Coligação": "UNIÃO / UNIÃO E TRABALHO",
    "Votação": 5.051,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO MIGUEL DE TAIPU",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "LAELSON ALBUQUERQUE",
    "Nome Urna": "LAELSON ALBUQUERQUE",
    "Partido / Coligação": "PP / O Trabalho Continua",
    "Votação": 4.589,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO SEBASTIÃO DE LAGOA DE ROÇA",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "PEDRO JUNIOR QUARESMA DE ARAUJO",
    "Nome Urna": "JÚNIOR DO CARACOL",
    "Partido / Coligação": "PSDB",
    "Votação": 3.998,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO SEBASTIÃO DO UMBUZEIRO",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "ADALCY MILÊNE DE FREITAS NEVES",
    "Nome Urna": "ADALCY FREITAS",
    "Partido / Coligação": "UNIÃO / O TRABALHO E O DESENVOLVIMENTO CONTINUAM",
    "Votação": 1.785,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SÃO VICENTE DO SERIDÓ",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ERIVAM DOS ANJOS LEONARDO",
    "Nome Urna": "ERIVAM DE BIU",
    "Partido / Coligação": "PSB / A VONTADE DO POVO É SEGUIR AVANÇANDO",
    "Votação": 5.176,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SAPÉ",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "SIDNEI PAIVA DE FREITAS",
    "Nome Urna": "MAJOR SIDNEI",
    "Partido / Coligação": "REPUBLICANOS / CONFIANÇA NO TRABALHO",
    "Votação": 22.518,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SERRA BRANCA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "MICHEL ALEXANDRE PEREIRA MARQUES",
    "Nome Urna": "ALEXANDRE",
    "Partido / Coligação": "UNIÃO / PRA SERRA BRANCA VENCER",
    "Votação": 5.355,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SERRA DA RAIZ",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "LUIZ GONZAGA BEZERRA DUARTE",
    "Nome Urna": "LUIZ MACHADO",
    "Partido / Coligação": "PSB / AMOR E TRABALHO POR SERRA DA RAIZ",
    "Votação": 2.186,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SERRA GRANDE",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "VICENTE ANTONIO DA SILVA NETO",
    "Nome Urna": "VICENTE",
    "Partido / Coligação": "PSB",
    "Votação": 2.218,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SERRA REDONDA",
    "Cargo": "Prefeito",
    "Nº": 22,
    "Candidato": "FRANCISCO BERNARDO DOS SANTOS",
    "Nome Urna": "CHICÃO",
    "Partido / Coligação": "PL / UNIDOS PELO DESENVOLVIMENTOS DA SERRA",
    "Votação": 4.212,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SERRARIA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ENÉIAS PEREIRA DA SILVA",
    "Nome Urna": "ENÉIAS CABÔCO",
    "Partido / Coligação": "PSB / SERRARIA SEGUE UNIDA",
    "Votação": 2.482,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SERTÃOZINHO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "RONALDO NOGUEIRA VIEIRA",
    "Nome Urna": "RONY VIEIRA",
    "Partido / Coligação": "PSB / O PROGRESSO CONTINUA",
    "Votação": 2.517,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SOBRADO",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "OLINALDO MARTINS DA SILVA",
    "Nome Urna": "LEO MARTINS",
    "Partido / Coligação": "MDB / A FORÇA DO POVO",
    "Votação": 3.478,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SOLÂNEA",
    "Cargo": "Prefeito",
    "Nº": 44,
    "Candidato": "JUCIAN JAD DO AMARAL COSTA",
    "Nome Urna": "JUCIAN JAD",
    "Partido / Coligação": "UNIÃO / SOLANEA SEGUE AVANÇANDO",
    "Votação": 8.826,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SOLEDADE",
    "Cargo": "Prefeito",
    "Nº": 11,
    "Candidato": "JOSÉ ALVES DE MIRANDA NETO",
    "Nome Urna": "MIRANDA NETO",
    "Partido / Coligação": "PP / UNIDOS PELA VERDADE",
    "Votação": 5.44,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SOSSÊGO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "VANUSA DA PAZ MEDEIROS",
    "Nome Urna": "VANUSA DE CARLINHOS",
    "Partido / Coligação": "REPUBLICANOS",
    "Votação": 1.733,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SOUSA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "HELDER MOREIRA ABRANTES DE CARVALHO",
    "Nome Urna": "HELDER CARVALHO",
    "Partido / Coligação": "PSB / SOUSA AINDA MAIOR",
    "Votação": 23.397,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "SUMÉ",
    "Cargo": "Prefeito",
    "Nº": 15,
    "Candidato": "MANOEL LOURENÇO QUEIROZ DUARTE",
    "Nome Urna": "MANEZINHO LOURENÇO",
    "Partido / Coligação": "MDB / A FORÇA DO POVO",
    "Votação": 6.128,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "TACIMA",
    "Cargo": "Prefeito",
    "Nº": 77,
    "Candidato": "LUIS RODRIGUES SOBRINHO",
    "Nome Urna": "XATÓ",
    "Partido / Coligação": "SOLIDARIEDADE / TACIMA SEGUE AVANÇANDO",
    "Votação": 3.778,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "TAPEROÁ",
    "Cargo": "Prefeito",
    "Nº": 45,
    "Candidato": "GEORGE CIRO MONTEIRO DE FARIAS",
    "Nome Urna": "GEORGE FARIAS",
    "Partido / Coligação": "PSDB",
    "Votação": 5.354,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "TAVARES",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "GENILDO JOSÉ DA SILVA",
    "Nome Urna": "CÔCO DE ODÁLIO",
    "Partido / Coligação": "PSB / Trabalho e Respeito",
    "Votação": 5.308,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "TEIXEIRA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "WENCESLAU SOUZA MARQUES",
    "Nome Urna": "WENCESLAU SOUZA MARQUES",
    "Partido / Coligação": "PSB / União pelo Trabalho",
    "Votação": 6.314,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "TENÓRIO",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "MANOEL VASCONCELOS",
    "Nome Urna": "MANOEL VASCONCELOS",
    "Partido / Coligação": "REPUBLICANOS / ALIANÇA PELO TRABALHO",
    "Votação": 1.85,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "TRIUNFO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "ESPEDITO CEZARIO DE FREITAS FILHO",
    "Nome Urna": "ESPEDITO FILHO",
    "Partido / Coligação": "PSB / \"O TRABALHO CONTINUA",
    "Votação": 5.104,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "UIRAÚNA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "MARIA SULENE DANTAS SARMENTO",
    "Nome Urna": "LENINHA ROMÃO",
    "Partido / Coligação": "PSB / UNIDOS PARA AVANÇAR",
    "Votação": 8.719,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "UMBUZEIRO",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "FERNANDA ISABEL LEAL MORAES DUARTE",
    "Nome Urna": "FERNANDA MORAES",
    "Partido / Coligação": "PSB / DO TRABALHO À VITÓRIA",
    "Votação": 3.599,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "VÁRZEA",
    "Cargo": "Prefeito",
    "Nº": 10,
    "Candidato": "PAULO NOBREGA DE MEDEIROS",
    "Nome Urna": "PROFESSOR PAULO NOBREGA",
    "Partido / Coligação": "REPUBLICANOS / FORTE É O POVO",
    "Votação": 1.538,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "VIEIRÓPOLIS",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "THIALLY ARISTOTELIS DE OLIVEIRA",
    "Nome Urna": "THIALLY",
    "Partido / Coligação": "PSB / MUITO MAIS POR VIEIRÓPOLIS",
    "Votação": 2.978,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "VISTA SERRANA",
    "Cargo": "Prefeito",
    "Nº": 40,
    "Candidato": "EMMANUEL DA NOBREGA DIAS",
    "Nome Urna": "EMMANUEL DE QUERUBINA",
    "Partido / Coligação": "PSB / UNIDOS POR VISTA SERRANA",
    "Votação": 1.829,
    "Situação": "Eleito"
  },
  {
    "": "",
    "Ano": 2024,
    "Turno": "1º Turno",
    "Localidade": "ZABELÊ",
    "Cargo": "Prefeito",
    "Nº": 55,
    "Candidato": "JORSÂMARA BEZERRA NEVES SILVA",
    "Nome Urna": "JORSÂMARA DE ZÉ INALDO",
    "Partido / Coligação": "PSD / TRABALHO, INOVAÇÃO E RESPEITO POR ZABELÊ",
    "Votação": 1.83,
    "Situação": "Eleito"
  }
]